{
 "title": "LUNAr updates",
 "tags": [ "Loki" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "All (5min)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({application=\"LUNAr\"} | json | line_format \"{{.channel_group}}\" != \"42\" [5m])) by (channel_group) ",
     "legendFormat": "{{channel_group}}"
    }
   ]
  },
  {
   "title": "Левый фронт",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (channel_title) (count_over_time({application=\"LUNAr\"} | json | channel_group=1 [24h]))",
     "legendFormat": "{{channel_title}}"
    }
   ]
  },
  {
   "title": "Левый тыл",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (channel_title) (count_over_time({application=\"LUNAr\"} | json | channel_group=2 [24h]))",
     "legendFormat": "{{channel_title}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (channel_title) (count_over_time({application=\"LUNAr\"} | json | channel_group=3 [24h]))",
     "legendFormat": "{{channel_title}}"
    }
   ]
  },
  {
   "title": "мемы",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(channel_title) (count_over_time({application=\"LUNAr\"} | json | channel_group=19[24h]))",
     "legendFormat": "{{channel_title}}"
    }
   ]
  },
  {
   "title": "Психология",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (channel_title) (rate({application=\"LUNAr\"} | json | channel_group=15 [$__auto]))",
     "legendFormat": "{{channel_title}}"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "logs",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "targets": [
    {
     "expr": "{application=\"LUNAr_test\"} | json | level = \"error\" "
    }
   ]
  },
  {
   "title": "ALL (1h)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({application=\"LUNAr\"} | json | line_format \"{{.channel_group}}\" != \"42\" [1h])) by (channel_group) ",
     "legendFormat": "{{channel_group}}"
    }
   ]
  }
 ]
}