global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: "traefik"
    static_configs:
      - targets: 
        - traefik:9089

  - job_name: "docker"
    static_configs:
      - targets:
        - 172.17.0.1:9323

  - job_name: "node-exporter"
    static_configs:
      - targets:
        - node-exporter:9100

  # - job_name: "my-node-exporter"
  #   static_configs:
  #     - targets:
  #       - nodexporter:9200

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets:
        - cadvisor:8080

